inertial_frame_id: world
waypoints:
  -
    point: [0, 2, -22]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [5, 2, -22]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [5, 7, -22]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 7, -22]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 5, -22]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [10, 20, -25]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  
  
