plugin_blacklist:
# common
- 3dr_radio
- actuator_control
- adsb
- altitude
- cam_imu_sync
- companion_process_status
- debug_value
- esc_status
- fake_gps
- ftp
- gps_rtk
- gps_status
- hil
- home_position
- landing_target
- log_transfer
- mocap_pose_estimate
- mount_control
- obstacle_distance
- odom
- onboard_computer_status
- param
- play_tune
- px4flow
- rangefinder

- safety_area
- setpoint_*
- trajectory
- vf4_hud
- vibration
- vision_*
- waypoint
- wheel_odometry
- wind_estimation


plugin_whitelist:
- 'sys_*'
- rc_io
